# Generated by Django 2.2.12 on 2020-04-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
