# Generated by Django 2.2.12 on 2020-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20200419_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-04-29T19:39:47.996964'),
            preserve_default=False,
        ),
    ]
